name: upload deps

on:
  workflow_dispatch:
    inputs:
      tag:
        default: "10.0.1"
        description: "Version, eg: 10.0.1"
        required: true

jobs:
  dotnet_runtime:
    runs-on: ubuntu-latest
    # if: ${{ github.repository_owner == 'MirrorChyan' }}
    strategy:
      fail-fast: false
      matrix:
        os: [win]
        arch: [arm64, x64]
    steps:
      - name: Download dotnet-runtime
        id: download_dotnet_runtime
        shell: bash
        run: |
          filename=windowsdesktop-runtime-${{ inputs.tag }}-${{ matrix.os }}-${{ matrix.arch }}.exe
          wget https://builds.dotnet.microsoft.com/dotnet/WindowsDesktop/${{ inputs.tag }}/$filename -O $filename

          echo "filename=$filename" | tee -a "$GITHUB_OUTPUT"

      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: local
          filename: ${{ steps.download_dotnet_runtime.outputs.filename }}
          mirrorchyan_rid: dotnet10
          version_name: ${{ inputs.tag }}

          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
